language: php
php:
  - '7.0'

before_script:
  - composer require satooshi/php-coveralls
  - composer install

script:
  - php vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
